package com.martinfou.trading.intelligence.pipeline;

import com.martinfou.trading.core.agent.StrategySpec;
import com.martinfou.trading.core.agent.StrategyProfile;

import java.util.List;
import java.util.Map;

/**
 * Generates compilable .java source code from a {@link StrategySpec}.
 *
 * Uses a template pattern with parameter substitution rather than
 * having the LLM generate raw Java. This ensures the output is
 * always structurally valid (compilable).
 *
 * The template produces a strategy in the {@code longterm} package
 * that follows Trading Bridge conventions: calcRiskPosition for
 * position sizing, closeOnly() for exits, ATR-based SL/TP.
 */
public class LtTemplateCodeGenerator {

    private static final String PACKAGE = "com.martinfou.trading.strategies.longterm";
    private static final String SOURCE_DIR = "trading-strategies/src/main/java/"
        + PACKAGE.replace('.', '/');

    private static final String TEMPLATE = """
package %s;

import com.martinfou.trading.core.*;
import com.martinfou.trading.core.indicators.Indicators;
import java.util.*;

/**
 * %3$s
 * <p>
 * Generated by Unified Strategy Engine.
 * Inspiration: %4$s
 * Profile: %5$s
 */
public class %1$s implements Strategy {

    private static final String NAME = "%1$s";
    private static final int LOOKBACK = %6$d;
    private static final int LOOKBACK_ATR = 14;
    private static final double ATR_SL_MULT = %.1f;
    private static final double ATR_TP_MULT = %.1f;
    private static final int MAX_HOLD_BARS = %7$d;
    private static final double REFERENCE_CAPITAL = 10_000;
    private static final double RISK_PCT = 0.01;

    private final String name;
    private final String symbol;
    private final List<Order> pending = new ArrayList<>();
    private final List<Bar> history = new ArrayList<>();
    private boolean inTrade = false;

    public %1$s() { this(NAME, "EUR_USD"); }
    public %1$s(String name) { this(name, "EUR_USD"); }
    public %1$s(String name, String symbol) {
        this.name = name;
        this.symbol = symbol;
    }

    @Override public String name() { return name; }

    @Override
    public void onBar(Bar bar) {
        history.add(bar);
        if (history.size() < LOOKBACK + 1) return;

        double atr = Indicators.atr(history, LOOKBACK_ATR);
        double close = bar.close();
        if (Double.isNaN(atr) || atr == 0) return;

        // Position sizing: risk-based
        long units = Indicators.calcRiskPosition(
            REFERENCE_CAPITAL, RISK_PCT, atr, ATR_SL_MULT, symbol);

        // Entry logic: %8$s
        if (!inTrade) {
            if (%9$s) {
                double sl = close - atr * ATR_SL_MULT;
                double tp = close + atr * ATR_TP_MULT;
                pending.add(new Order(symbol, Order.Side.BUY, Order.Type.MARKET, units, close)
                    .withStopLoss(sl).withTakeProfit(tp));
                inTrade = true;
                return;
            }
            if (%10$s) {
                double sl = close + atr * ATR_SL_MULT;
                double tp = close - atr * ATR_TP_MULT;
                pending.add(new Order(symbol, Order.Side.SELL, Order.Type.MARKET, units, close)
                    .withStopLoss(sl).withTakeProfit(tp));
                inTrade = true;
                return;
            }
        }

        // Exit logic: %11$s
        if (inTrade && history.size() > LOOKBACK + MAX_HOLD_BARS) {
            exitTrade(close);
        }
    }

    private void exitTrade(double price) {
        Order.Side exit = inTrade ? Order.Side.SELL : Order.Side.BUY;
        pending.add(new Order(symbol, exit, Order.Type.MARKET, 1000, price).closeOnly());
        inTrade = false;
    }

    @Override public void onTick(double bid, double ask, long volume) {}

    @Override
    public List<Order> getPendingOrders() {
        List<Order> copy = new ArrayList<>(pending);
        pending.clear();
        return copy;
    }

    @Override
    public void reset() {
        history.clear(); pending.clear();
        inTrade = false;
    }
}
""";

    /**
     * Generates the .java source file content for a given strategy spec.
     */
    public String generate(StrategySpec spec) {
        String className = sanitizeClassName(spec.name());
        int lookback = extractLookback(spec);
        int maxHoldBars = spec.maxHoldBars();

        String longCondition = buildCondition(spec.longEntry(), "close", lookback);
        String shortCondition = buildCondition(spec.shortEntry(), "close", lookback);
        String exitDesc = spec.exitCondition() != null ? spec.exitCondition() : "MAX_HOLD";

        return String.format(TEMPLATE,
            className,                           // 1 - class name
            PACKAGE,                             // 2 - package
            spec.description(),                  // 3 - description
            spec.inspiration(),                  // 4 - inspiration
            spec.profile(),                      // 5 - profile
            lookback,                            // 6 - lookback
            maxHoldBars,                         // 7 - max hold bars
            spec.category(),                     // 8 - entry desc
            longCondition,                       // 9 - long entry condition
            shortCondition,                      // 10 - short entry condition
            exitDesc                             // 11 - exit desc
        );
    }

    /**
     * Returns the file path where the generated .java should be written.
     */
    public String filePath(StrategySpec spec) {
        return SOURCE_DIR + "/" + sanitizeClassName(spec.name()) + ".java";
    }

    private String sanitizeClassName(String name) {
        return name.replaceAll("[^a-zA-Z0-9]", "");
    }

    private int extractLookback(StrategySpec spec) {
        Object val = spec.params().getOrDefault("lookback", 20);
        if (val instanceof Number n) return n.intValue();
        return 20;
    }

    private String buildCondition(String condition, String priceVar, int lookback) {
        if (condition == null || condition.isBlank()) return "false";
        return condition
            .replace("CLOSE", priceVar)
            .replace("LOOKBACK", String.valueOf(lookback));
    }
}
